apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-jenkins
  namespace: coba-namespace
spec:
  selector:
    matchLabels:
      app: test-jenkins
  replicas: 2
  template:
    metadata:
      labels:
        app: test-jenkins
    spec:
      containers:
      - name: test-jenkins
        image: anang05/app-coba:v2
        ports:
        - containerPort: 80
      restartPolicy: Always