apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: aplikasi-iscip-namespaces
spec:
  selector:
    matchLabels:
      app: nginx-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - name: nginx-deployment
        image: nginx:1.16.1 # Update the version of nginx from 1.14.2 to 1.16.1
        ports:
        - containerPort: 80
      restartPolicy: Always
     
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
  namespace: aplikasi-iscip-namespaces
  labels:
    app: nginx-deployment
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30024
  selector:
    app: nginx-deployment   
