apiVersion: v1
kind: Service
metadata:
  name: test-jenkins
  namespace: coba-namespace
  labels:
    app: test-jenkins
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30014
  selector:
    app: test-jenkins